### ISSUE TITLE
Regarding Private mode, node based BYOL license was discontinued now so could you please add notice at private mode section?

### ISSUE THREAD

**Issue by imasafum** [NetAppDocs/bluexp-setup-admin.ja-jp#2]
### Page URL

https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html#private-mode

### Page title

Private mode

### Summary

Regrading Private mode, node based BYOL license was discontinued so could you please add notice at private mode section.
For example, "Due to the end-of-life of the node-based license, new users are not currently able to deploy in private mode."
This is just an idea, so I am sure there are other good announcement ideas.
Best regards,

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-bcammett** [comment]
@imasafum,

Thank you for noticing this and submitting an issue. I'm reaching out to the product team for additional clarification.

Thanks again,
Ben

**Comment by netapp-bcammett** [comment]
Node-based licensing is still supported with private mode deployments.

Regards,
Ben
