### ISSUE TITLE
At Step 2: Set up BlueXP, "d. Select Enable restricted mode on this account." was not apear.

### ISSUE THREAD

**Issue by imasafum** [NetAppDocs/bluexp-setup-admin.ja-jp#3]
### Page URL

https://docs.netapp.com/ja-jp/bluexp-setup-admin/task-install-restricted-mode.html

### Page title

コネクタを制限モードで展開します

### Summary

Customer said that At Step 2: Set up BlueXP, "d. Select Enable restricted mode on this account." was not apear.
If the customer's comments are correct, e.g., due to an update to A, could you please replace the screenshot?
Best regards,

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-bcammett** [comment]
Hi @imasafum,

It should be there. The customer needs to open a support case.

Thanks,
Ben
